---
title: "Tablas"
format: html
editor: visual
---

```{r}
#| echo: false
#| message: false
library(datos)
library(gt)
library(gtsummary)
library(broom)
library(dplyr)
library(tidyr)
```

## Tablas de resumen con gtsummary

```{r}
theme_gtsummary_language(
  language = "es",
  big.mark = ""
)

```

```{r}
pinguinos |> 
  filter(isla == "Biscoe") |> 
  select(-c(isla, anio, especie)) |> 
  drop_na() |> 
  tbl_summary()
```

```{r}
pinguinos %>% 
  filter(isla == "Biscoe") %>% 
  select(-c(isla, anio, especie)) %>% 
  drop_na() %>% 
  tbl_summary(
    statistic = list(
      all_continuous() ~ "{mean} ({sd})"
    )
  ) |> 
  modify_footnote(
    update = list(
      all_stat_cols() ~ "Media (desviación estándar); Recuento (%)"
    )
  )
```

```{r}
pinguinos %>% 
  filter(isla == "Biscoe") %>% 
  select(-c(isla, anio, especie)) %>% 
  drop_na() %>% 
  tbl_summary(
    statistic = list(
      all_continuous() ~ "{mean} ({sd})"
    ),
    by = "sexo",
    label = list(
      masa_corporal_g ~ "Masa corporal (gramos)"
    )
  ) |> 
  modify_footnote(
    update = list(
      all_stat_cols() ~ "Media (desviación estándar); Recuento (%)"
    )
  ) |> 
  add_p() |> 
  modify_spanning_header(
    all_stat_cols() ~ "**Sexo**"
  ) |> 
  modify_header(
    update = list(
      label ~ "**Variable**",
      p.value ~ "**valor p**"
    )
  )
```

## Tablas con gt

El uso más simple, sería crear una tabla a partir de un dataframe

```{r}
filter(paises, anio == 2007) |> 
  group_by(continente) |> 
  slice_max(poblacion, n = 3) |> 
  gt() |> 
  tab_header(title = "Países con mayor población en el año 2007",
             subtitle = "Segun continente") |> 
  tab_footnote(footnote = "Estos son los únicos dos países de Oceanía incluidos en esta base de datos",
               locations = cells_body(
                 columns = pais, 
                 rows = 13:14
               )) |> 
  tab_source_note(source_note = "Fuente: gapminder.org") |> 
  tab_spanner(label = "Variables de desarrollo medidas", columns = 4:6)
```

Otro ejemplo: crear una tabla con las variables de mi set de datos

```{r}
data.frame(variable = names(paises),
           descripción = c(
             "País (factor de 142 niveles)",
             "Continente en que se encuentra el país",
             "Año de la observación",
             "..",
             "...",
             "..."
           )) |> 
  gt()
```

## broom para convertir los resultados de un modelo en un dataframe

```{r}
modelo <- lm(masa_corporal_g ~ largo_aleta_mm + largo_pico_mm, data = pinguinos)

summary(modelo)
```

```{r}
tidy(modelo) |>  gt()
glance(modelo) |> gt()
augment(modelo) |> gt()
```
